---
version: 1.0
description: A basic sequential workflow for the dpi patching automation.

input:
  - servername

vars:
  - message: null
  - result: null

output:
  - result: <% ctx().message %>

tasks:
  servershutdown:
    action: core.echo message="Automation started"
    # input:
    #   servername: [<% ctx().servername %>]
    next:
      - when: <% succeeded() %>
        do: finish

      - when: <% failed() %>
        do: stop

finish:
    action: core.echo message="Automation completed."

    stop:
      action: core.echo message="Automation stopped."
      next:
        - do: fail
    

