---
- hosts: webservers
  become: true
  become_method : sudo 
  become_user: root
  tasks: 
    - name: Installing apache module
      yum: 
        name: httpd 
        state: latest

    - name: restarting service  
      service: 
        name: httpd
        state: restarted

      
      



