---
- hosts: groupA
  become: true
  become_method: sudo
  become_user: root
  max_fail_percentage: 10  #Abort the playbook if failed percentage morethan specified
  tasks:
    - name: Checking running Process
      shell: |
        printf "\n"
        ps -e -o user,pid,ppid,args |grep '[appedt, httpd]' |egrep '[tomee,httpd]' > /dev/null 2>1
        if [[ $? -eq 0 ]]                                                   #$? Register the output of most recent command
            then 
            printf "\n"
            printf "\t OK: Apache Httpd and Tomee applications are running...\n"
            else
            printf "\t  Error: No Process are running.. \n"
        fi
      changed_when: false
      register: service_apache_status     # Register the shell script command output
      become: true
      become_method: sudo
      become_user: appedt
      failed_when: service_apache_status.rc!=0
    - debug: var=service_apache_status.stdout_lines