---
- hosts: webservers
  become: true
  become_user: root
  become_method: sudo
  
  tasks: 
    - name: copying files to /var/www/html
      copy:
        src: /var/tmp/copy/{{ item }}
        dest: /var/www/html/
        with_items: 
          - index.html
          - script.js
          - http_check.yaml