---
- hosts: appservers
  become: true
  become_user: appedt
  become_method: sudo
  tasks:
   - name: Copy a file 
     copy:
      src: /tmp/copyfile.txt
      dest: /tmp/copyfile2.txt
      owner: appedt
      group: appedt
      mode: 0777
     when: ansible_distribution == "RedHat" ansible_distribution_major_version== '7'
    