---
- hosts: webservers
  become: true
  become_user: root
  become_method: sudo
  
  tasks: 
    - name: copying files to /var/www/html
      copy:
        src: /var/tmp/copy/
        dest: /var/www/html/
 