---
- hosts: groupA
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Checking running Process
      shell: ps -ef|grep appedt|egrep ['apache, httpd']
      ignore_errors: yes
      changed_when: false
      register: service_apache_status
      become: true
      become_method: sudo
      become_user: appedt
      failed_when: service_apache_status.rc!=0 or service_apache_status.rc<2
      
    - name: Stopping pawnee Apache Tomee Applications
      when: '"ps -ef|grep pawnee|egrep start" > 0'
      shell: /opt/gsit/pawnee/apache-tomee-plus/bin/shutdown.sh
      register: pawnee_stop_status
      become: true
      become_method: sudo
      become_user: appedt
      #    - debug: var=pawnee_stop_status.stdout_lines  #this line will be used to display the output registered in "pawnee_stop_status"

    - name: Stopping shawnee Apache Tomee Applications
      when: '"ps -ef|grep shawnee|egrep start" > 0'
      shell: /opt/gsit/shawnee/apache-tomee-plus/bin/shutdown.sh
      register: shawnee_stop_status
      become: true
      become_method: sudo
      become_user: appedt
    #- debug: var=shawnee_stop_status.stdout.lines

    - name: Stopping sioux Apache Tomee Applications
      when: '"ps -ef|grep sioux|egrep start" > 0'
      shell: /opt/gsit/sioux/apache-tomee-plus/bin/shutdown.sh
      register: sioux_stop_status
      become: true
      become_method: sudo
      become_user: appedt
    #- debug: var=sioux_stop_status.stdout.lines

    - name: Stopping Apache Httpd 
      when: '"ps -ef|grep httpd|egrep start" > 0'
      shell: /opt/gsit/httpd/lbin/apache-stop.sh
      register: apache_httpd_stop_status
      become: true
      become_method: sudo
      become_user: appedt
    #- debug: var=apache_httpd_stop_status       

    