---
- hosts: appservers
  become: true
  become_method: sudo
  become_user: appedt
  tasks:
   - name: "Installing httpd service"
     yum: 
       pkg: httpd
       state: present
       installroot: /opt/gsit
   - name: Restarting httpd service
     service: 
       name: httpd
       status: enabled
       state: restarted