---
- hosts: sbservers
  become: true
  become_method: sudo
  become_user: automation
  tasks:
    - name: "Checking Apache httpd status"
       uri:
         url: "http://localhost:8000"
         status_code: 200
       register: result
       until: result.status == 200
       retries: 90
       delay: 10    #test
