---
- hosts: appservers
  become: true
  become_method: sudo
  become_user: appedt
  tasks:
    - name: Installing httpd service
      yum: 
       pkg: httpd
       enable: true
       state: present
       owner: appedt
       group: appedt
       mode: 0750
       
      service: 
       name: httpd
       state: started
       