---
- hosts: groupA
  become: true
  become_method: sudo
  become_user: root
  max_fail_percentage: 10  #Abort the playbook if failed percentage morethan specified
  tasks:
    - name: Checking running Process
      shell: ps -ef|grep appedt|egrep ['apache, httpd']
      changed_when: false
      register: service_apache_status     # Register the shell script command output
      become: true
      become_method: sudo
      become_user: appedt
      failed_when: service_apache_status.rc!=0
      
    - name: Stopping pawnee Apache Tomee Applications
      when: '"ps -ef|grep pawnee|egrep start" > 0'
      shell: /opt/gsit/pawnee/apache-tomee-plus/bin/shutdown.sh
      register: pawnee_stop_status
      become: true
      become_method: sudo
      become_user: appedt
      vars:
        ansible_command_timeout: 7200
      #    - debug: var=pawnee_stop_status.stdout_lines  #this line will be used to display the output registered in "pawnee_stop_status"
      
    - name: Stopping shawnee Apache Tomee Applications
      when: '"ps -ef|grep shawnee|egrep start" > 0'
      shell: /opt/gsit/shawnee/apache-tomee-plus/bin/shutdown.sh
      register: shawnee_stop_status
      become: true
      become_method: sudo
      become_user: appedt
      vars:
        ansible_command_timeout: 7200
    #- debug: var=shawnee_stop_status.stdout.lines
    
    
    - name: Stopping sioux Apache Tomee Applications
      when: '"ps -ef|grep sioux|egrep start" > 0'
      shell: /opt/gsit/sioux/apache-tomee-plus/bin/shutdown.sh
      register: sioux_stop_status
      become: true
      become_method: sudo
      become_user: appedt
      vars:
        ansible_command_timeout: 7200
    #- debug: var=sioux_stop_status.stdout.lines

    - name: Stopping Apache Httpd 
      when: '"ps -ef|grep httpd|egrep start" > 0'
      shell: /opt/gsit/httpd/lbin/apache-stop.sh
      register: apache_httpd_stop_status
      become: true
      become_method: sudo
      become_user: appedt
      vars:
        ansible_command_timeout: 300
    #- debug: var=apache_httpd_stop_status       

    - name: Apply security patches and updates on remote hosts
      become: true
      become_method: sudo
      become_user: root
      yum:
        name: "*"
        state: latest
        
    - name: Comparing last Kernel and reboot if Kernel version changed
      become: true
      become_method: sudo
      become_user: root
      shell: |
        LAST_KERNEL=$(rpm -q --last kernel | perl -pe 's/^kernel-(\S+).*/$1/' | head -1)
        CURRENT_KERNEL=$(uname -r)
        
        if [[ $LAST_KERNEL != $CURRENT_KERNEL ]]; then
        "sleep 5 && shutdown -r now"
      when: ansible_distribution== 'Red Hat Enterprise Linux' and ansible_major.release == '6'
      
    - name: Wait for the system to reboot 
      wait_for_connection:
        connect_timeout: 20
        sleep: 7200 
        delay: 5
        timeout: 60
        
    - name: Starting Apache HTTPD
      shell: /opt/gsit/httpd/lbin/apache-start.sh
      register: apache-start_status
      timeout: 300
      become: true
      become_method: sudo
      become_user: appedt
      
      