---
- hosts: groupA
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Checking running Process
      shell: "ps -ef |grep appedt"
      ignore_errors: yes
      changed_when: false
      register: service_apache_status
      become: true
      become_method: sudo
      become_user: appedt
      
    - debug: var=service_apache_status.stdout_lines
      
    - name: Stopping pawnee Apache Tomee Applications
      shell: /opt/gsit/pawnee/apache-tomee-plus/bin/shutdown.sh
      register: pawnee_stop_status
      become: true
      become_method: sudo
      become_user: appedt
    - debug: var=pawnee_stop_status.stdout.find ("Tomcat stopped.")!=0
    
    -name: Send and email when Applications are not running
     mail:
       host: 127.0.0.1
       port: 25
       subject: Ansible Report
       body: Hello, This is an email regarding Patching Automation
       from: hdamacha@starbucks.com
       to: hdamacha@starbucks.com
       attach: pawnee_stop_status.stdout.lines
     delegate_to: localhost
       -
      