---
- hosts: groupA
  become: true
  become_method: sudo
  become_user: appedt
  tasks:
    - name: Checking running Process
      shell: "ps -eo user,args,pid |grep appedt>/tmp/status.txt && cat /tmp/status.txt"
      ignore_errors: yes
      changed_when: false
      register: service_apache_status
